name: LessDuplications
main: LessDuplications.LDMain
version: 1.2
author: MegaFlary, nikes64
website: 'http://gametk.net/'
commands:
  ld:
    description: Main LessDuplications command.
    usage: |
           /<command> reload - перезагрузить конфиг.
    permission: lessduplications.command